apiVersion: v1
kind: Service
metadata:
  name: sensordataapi
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 7888
      targetPort: 80
      nodePort: 30010
  selector:
    app: sensordataapi

