apiVersion: v1
kind: Service
metadata:
  name: couchbase
spec:
  ports:
    - name: "7091"
      port: 7091
      targetPort: 8091
    - name: "7092"
      port: 7092
      targetPort: 8092
    - name: "7093"
      port: 7093
      targetPort: 8093
    - name: "7094"
      port: 7094
      targetPort: 8094
    - name: "12207"
      port: 12207
      targetPort: 11207
    - name: "12208"
      port: 12208
      targetPort: 11208
    - name: "12209"
      port: 12209
      targetPort: 11209
    - name: "12210"
      port: 12210
      targetPort: 11210
  selector:
    app: couchbase
